# C flags
cflags-y	+= -Os
CFLAGS_lazyplug.o			+= -finline-functions

# HotPlugs #

obj-$(CONFIG_ALUCARD_HOTPLUG)           += alucard_hotplug.o
obj-$(CONFIG_ASMP)           	        += autosmp.o
obj-$(CONFIG_BLU_PLUG)                  += blu_plug.o
obj-$(CONFIG_BRICKED_HOTPLUG)           += bricked_hotplug.o
obj-$(CONFIG_DYNAMIC_HOTPLUG)           += dynamic_hotplug.o
obj-$(CONFIG_INTELLI_PLUG)              += intelli_plug.o
obj-$(CONFIG_LAZYPLUG)                  += lazy_plug.o
obj-$(CONFIG_MSM_HOTPLUG)		+= msm_hotplug.o
obj-$(CONFIG_MSM_SLEEPER)		+= msm_sleeper.o
obj-$(CONFIG_ZEN_DECISION)              += msm_zen_decision.o
obj-$(CONFIG_STATE_NOTIFIER)		+= state_notifier.o
obj-$(CONFIG_THUNDER_PLUG)              += thunder_plug.o
